### ISSUE TITLE
Changed behavior in sequence.assemble

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#31]
It seems like Sequence.assemble() method is changed. Thus, the example here:

https://pysbol2.readthedocs.io/en/latest/sbol_examples.html

is not fully functional although it used to. 
The problematic part is `gene_seq.assemble()`
Any ideas @bbartley?

**Comment by bbartley** [comment]
The assemble method is failing because the Sequences have not been added to the Document.  The problem actually occurs doc.addSequence([..,...,...]).  Document.addSequence() doesn't currently accept lists as an argument (althoughthe C++ library does allow a vector of Sequence pointers, but this function hasn't been fully wrapped).  Instead, the user has to specify one Sequence object at a time, eg, doc.addSequence(seq_obj).
