### ISSUE TITLE
Update API doc

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#32]
Some fields in API doc are missing. Either add them or remove it if it's not suppose to be accessible.

**Comment by bbartley** [comment]
Utility functions in the C++ API which are not meant to be exposed are now hidden with Doxygen conditional statements.

API documentation can be further improved by the following:
* Documentation for constructors shows an optional arguments dictionary *args, but it should explicitly show the expected arguments (presumably this happens when 
* Class documentation should show inherited members
* If possible, URIProperty, TextProperty, IntProperty, VersionProperty, OwnedObject, ReferencedObject classes should be grouped together
* SWIG instantiations of templated classes such as listOf*, owned*, or *Property should NOT be documented

**Comment by kirichoi** [comment]
Fixed by commit SynBioDex/libSBOL@1de702e5ebe47484c6918a24bafd5c5d213d9678
