### ISSUE TITLE
Incorrect object is returned when full URI is not used

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#37]
In functions such as getComponentDefinition(), incorrect object is returned when full URI is not supplied.

**Comment by bbartley** [comment]
This error occurred for two reasons:  1)  at the user level, because the user was trying to retrieve a top level object from a Document by its displayId (rather than persistentId),  2) at the code level, because of sloppy pattern matching when looking up a top level object by the user's argument.  The second issue has been corrected.  For the first issue, we need to discuss further if we want to allow looking up top level objects by their displayId in addition to their persistentId
