### ISSUE TITLE
Module version is inaccessible in Python 2.7 but seems to be OK in 3.6

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL#56]
```
>>> sbol.__version__
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'

**Comment by kirichoi** [comment]
Hmm, seems to be working fine on my machine. Was it installed from PyPI? And which version are you testing?

**Comment by kirichoi** [comment]
Also, if this issue is specific to Mac OSX, it could be due to incorrectly configured folder structure. Everything under https://github.com/SynBioDex/pySBOL/tree/master/Mac_64_2/sbol for example, must be installed under a folder name `sbol` in `site-packages` (or `dist-packages` in Mac) directory. That way, when `import sbol` is run in Python, it will look for the folder and initialize with `__init__.py` script.

**Comment by bbartley** [comment]
It's working now.  I must have had an old version hanging out on my machine.
